#!/bin/bash

while [[ $# -gt 0 ]]; do
  case "$1" in
    -K) shift ;;
    -s) ;;
    -H) shift ;;
    *) URL=$1 ;;
  esac
  shift
done

cat-maybe-gzip() {
  if [ -f "$1" ]; then
    # unfortunately, just because a file lacks the gzip extension, in some bundles it still may be gzipped :(
    gunzip -c -q $1 || cat $1
  else
    gunzip -c ${1}.gz
  fi
}


path-filename() {
  # we ignore query strings
  echo ${URL_HOSTNAME}_master/${URL_PORT}${BUNDLE_PORT_DELIMITER}master_$(echo "$1" | cut -f 1 -d ? | sed 's|/|_|g').json
}

cat-path() {
  local URL_PATH="$1"
  if (echo "$URL_PATH" | egrep -q '^tasks(\?|$)'); then
    # /tasks data is too sparse, and we don't support pagination (because snapshot). Reassemble tasks data from state endpoint.
    RECONST_FILENAME="$(path-filename tasks-reconst)"
    if [ ! -f "$RECONST_FILENAME" ]; then
      ( printf '{"tasks":'
        cat-path "state" | jq -M -c '.frameworks | map([.tasks, .unreachable_tasks, .completed_tasks]) | flatten'
        printf '}'
      ) | gzip > "$RECONST_FILENAME"
    fi
    cat-path "tasks-reconst"
  else
    cat-maybe-gzip $(path-filename "$URL_PATH")
  fi
}

URL_AUTHORITY=$(echo "$URL" | cut -f 3 -d /)
URL_PATH=$(echo "$URL" | cut -f 4-9 -d /)
URL_HOSTNAME=$(echo $URL_AUTHORITY | cut -f 1 -d :)
URL_PORT=$(echo $URL_AUTHORITY | cut -f 2 -d :)

cat-path "$URL_PATH"
