#!/usr/bin/env bash

_comp_marathon_join-str() {
  delimiter="$1"
  shift
  OUTPUT=""
  for ((n=1; n<=$#; n++)); do
    if [ "$n" -ne 1 ]; then
      OUTPUT+="${delimiter}"
    fi
    OUTPUT+="${!n}"
  done
  echo -n "$OUTPUT"
}

_comp_marathon_curl() {
  case "${prev}" in
    curl)
      COMPREPLY+=( $(compgen -W "/metrics /v2/apps /v2/tasks /v2/deployments /v2/eventSubscriptions /v2/groups /v2/info /v2/leader /v2/queue /v2/tasks /v2/pods" -- "${cur}"))
      return 0
      ;;
  esac
}

_comp_marathon_pod_instance_list() {
  case "${cur}" in
    -*)
      COMPREPLY+=( $(compgen -W "--all --sort -s --columns -c --no-header --no-align --help" -- "${cur}"))
      return 0
      ;;
  esac

  case "${prev}" in
    -c|--columns|-s|--sort)
      local cols curcol others n
      cols=($(echo "$cur" | tr ',' ' '))
      if [ ! ${#cols[@]} = 0 ]; then
        if [ "${cur:${#cur}-1}" = "," ]; then
          cols+=("")
        fi

        curcol=${cols[${#cols[@]}-1]}
        others=$(_comp_marathon_join-str , "${cols[@]:0:${#cols[@]}-1}")
      else
        others=""
        curcol=""
      fi

      COMPREPLY+=( $(compgen -W "default id agentHostname agentId status statusSince specReferences lastUpdated lastChanged cpus mem disk gpus containerCount volumeCount networkCount" -- "${curcol}"))

      if [ ! -z "$others" ]; then
        for ((n=0; n<${#COMPREPLY[@]}; n++)); do
          COMPREPLY[$n]="${others},${COMPREPLY[n]}"
        done
      fi

      return 0
      ;;
  esac
}

_comp_marathon_app_instance_list() {
  case "${cur}" in
    -*)
      COMPREPLY+=( $(compgen -W "--all --sort -s --columns -c --no-header --no-align --help" -- "${cur}"))
      return 0
      ;;
  esac

  case "${prev}" in
    -c|--columns|-s|--sort)
      local cols curcol others n
      cols=($(echo "$cur" | tr ',' ' '))
      if [ ! ${#cols[@]} = 0 ]; then
        if [ "${cur:${#cur}-1}" = "," ]; then
          cols+=("")
        fi

        curcol=${cols[${#cols[@]}-1]}
        others=$(_comp_marathon_join-str , "${cols[@]:0:${#cols[@]}-1}")
      else
        others=""
        curcol=""
      fi

      COMPREPLY+=( $(compgen -W "default id host appId stagedAt startedAt state version ports servicePorts ipAddresses agentId hcAlive hcFirstSuccess hcLastFailure hcConsecutiveFailures" -- "${curcol}"))
      if [ ! -z "$others" ]; then
        for ((n=0; n<${#COMPREPLY[@]}; n++)); do
          COMPREPLY[$n]="${others},${COMPREPLY[n]}"
        done
      fi

      return 0
      ;;
  esac
}

# compgen doesn't handle dollar signs well :( we have to double escape them
_compsafe() {
  sed 's/\$/\\\\\\$/g'
}

_comp_marathon_pod_instance_kill() {
  case "${cur}" in
    -*)
      COMPREPLY+=( $(compgen -W "--help --color --no-color --wipe" -- "${cur}"))
      return 0
      ;;
    *)
      COMPREPLY+=( $(compgen -W "$(marathon-cli pod instance list -c id --no-header --no-align | _compsafe)" -- "${cur}"))
      return 0
      ;;
  esac
}

_comp_marathon_app_instance_kill() {
  case "${cur}" in
    -*)
      COMPREPLY+=( $(compgen -W "--help --color --no-color --scale --wipe" -- "${cur}"))
      return 0
      ;;
    *)
      COMPREPLY+=( $(compgen -W "$(marathon-cli app instance list -c id --no-header --no-align | _compsafe)" -- "${cur}"))
      return 0
      ;;
  esac
}

_comp_marathon_app_instance_show() {
  case "${cur}" in
    -*)
      COMPREPLY+=( $(compgen -W "--help --color --no-color" -- "${cur}"))
      return 0
      ;;
    *)
      COMPREPLY+=( $(compgen -W "$(marathon-cli app instance list -c id --no-header --no-align | _compsafe)" -- "${cur}"))
      return 0
      ;;
  esac
}

_comp_marathon_app_restart() {
  case "${cur}" in
    -*)
      COMPREPLY+=( $(compgen -W "--help --color --no-color --force" -- "${cur}"))
      return 0
      ;;
    *)
      COMPREPLY+=( $(compgen -W "$(marathon-cli app list -c id --no-header --no-align)" -- "${cur}"))
      return 0
      ;;
  esac
}

_comp_marathon_app_scale() {
  case "${cur}" in
    -*)
      COMPREPLY+=( $(compgen -W "--help --color --no-color --force --instances" -- "${cur}"))
      return 0
      ;;
    *)
      COMPREPLY+=( $(compgen -W "$(marathon-cli app list -c id --no-header --no-align)" -- "${cur}"))
      return 0
      ;;
  esac
}

_comp_marathon_app_delete() {
  case "${cur}" in
    -*)
      COMPREPLY+=( $(compgen -W "--help --color --no-color --force" -- "${cur}"))
      return 0
      ;;
    *)
      COMPREPLY+=( $(compgen -W "$(marathon-cli app list -c id --no-header --no-align)" -- "${cur}"))
      return 0
      ;;
  esac
}

_comp_marathon_pod_delete() {
  case "${cur}" in
    -*)
      COMPREPLY+=( $(compgen -W "--help --color --no-color" -- "${cur}"))
      return 0
      ;;
    *)
      COMPREPLY+=( $(compgen -W "$(marathon-cli pod list -c id --no-header --no-align)" -- "${cur}"))
      return 0
      ;;
  esac
}

_comp_marathon_pod_show() {
  case "${cur}" in
    -*)
      COMPREPLY+=( $(compgen -W "--help --color --no-color" -- "${cur}"))
      return 0
      ;;
    *)
      COMPREPLY+=( $(compgen -W "$(marathon-cli pod list -c id --no-header --no-align)" -- "${cur}"))
      return 0
      ;;
  esac
}

_comp_marathon_pod_edit() {
  case "${cur}" in
    *)
      COMPREPLY+=( $(compgen -W "$(marathon-cli pod list -c id --no-header --no-align)" -- "${cur}"))
      return 0
      ;;
  esac
}

_comp_marathon_pod() {
  if [ ${COMP_CWORD} = 2 ]; then
    COMPREPLY=( $(compgen -W "show list instance delete edit" -- ${cur}) )

    return 0
  fi

  cmd=${COMP_WORDS[2]}

  case "$cmd" in
    show) _comp_marathon_pod_show ;;
    delete) _comp_marathon_pod_delete ;;
    list) _comp_marathon_pod_list ;;
    instance) _comp_marathon_pod_instance ;;
    edit) _comp_marathon_pod_edit ;;
  esac
}

_comp_marathon_app_instance() {
  if [ ${COMP_CWORD} = 3 ]; then
    COMPREPLY=( $(compgen -W "kill list show" -- ${cur}) )

    return 0
  fi

  cmd=${COMP_WORDS[3]}

  case "$cmd" in
    kill) _comp_marathon_app_instance_kill ;;
    show) _comp_marathon_app_instance_show ;;
    list) _comp_marathon_app_instance_list ;;
  esac
}

_comp_marathon_pod_instance() {
  if [ ${COMP_CWORD} = 3 ]; then
    COMPREPLY=( $(compgen -W "kill list" -- ${cur}) )

    return 0
  fi

  cmd=${COMP_WORDS[3]}

  case "$cmd" in
    kill) _comp_marathon_pod_instance_kill ;;
    list) _comp_marathon_pod_instance_list ;;
  esac
}

_comp_marathon_pod_list() {
  case "${cur}" in
    -*)
      COMPREPLY+=( $(compgen -W "--all --sort -s --columns -c --no-header --no-align --help" -- "${cur}"))
      return 0
      ;;
  esac

  case "${prev}" in
    -c|--columns|-s|--sort)
      local cols curcol others n
      cols=($(echo "$cur" | tr ',' ' '))
      if [ ! ${#cols[@]} = 0 ]; then
        if [ "${cur:${#cur}-1}" = "," ]; then
          cols+=("")
        fi

        curcol=${cols[${#cols[@]}-1]}
        others=$(_comp_marathon_join-str , "${cols[@]:0:${#cols[@]}-1}")
      else
        others=""
        curcol=""
      fi

      COMPREPLY+=( $(compgen -W "default id lastChanged lastUpdated status statusSince instances version instanceCount containerCount instanceStatuses imageKinds imageIds volumeMountCounts resources cpus mem disk gpus totalResources totalCpus totalMem totalDisk totalGpus" -- "${curcol}"))
      if [ ! -z "$others" ]; then
        for ((n=0; n<${#COMPREPLY[@]}; n++)); do
          COMPREPLY[$n]="${others},${COMPREPLY[n]}"
        done
      fi

      return 0
      ;;
  esac
}

_comp_marathon_app_edit() {
  case "${cur}" in
    -*)
      COMPREPLY+=( $(compgen -W "--help --color --no-color" -- "${cur}"))
      return 0
      ;;
    *)
      COMPREPLY+=( $(compgen -W "$(marathon-cli app list -c id --no-header --no-align)" -- "${cur}"))
      return 0
      ;;
  esac
}

_comp_marathon_app_show() {
  case "${cur}" in
    -*)
      COMPREPLY+=( $(compgen -W "--help --color --no-color" -- "${cur}"))
      return 0
      ;;
    *)
      COMPREPLY+=( $(compgen -W "$(marathon-cli app list -c id --no-header --no-align)" -- "${cur}"))
      return 0
      ;;
  esac
}

_comp_marathon_app() {
  if [ ${COMP_CWORD} = 2 ]; then
    COMPREPLY=( $(compgen -W "show list instance delete edit" -- ${cur}) )

    return 0
  fi

  cmd=${COMP_WORDS[2]}

  case "$cmd" in
    show) _comp_marathon_app_show ;;
    delete) _comp_marathon_app_delete ;;
    list) _comp_marathon_app_list ;;
    instance) _comp_marathon_app_instance ;;
    edit) _comp_marathon_app_edit ;;
    scale) _comp_marathon_app_scale ;;
    restart) _comp_marathon_app_restart ;;
  esac
}

_comp_marathon_queue() {
  case "${cur}" in
    -*)
      COMPREPLY+=( $(compgen -W "--all --sort -s --columns -c --no-header --no-align --help" -- "${cur}"))
      return 0
      ;;
  esac

  case "${prev}" in
    -c|--columns|-s|--sort)
      local cols curcol others n
      cols=($(echo "$cur" | tr ',' ' '))
      if [ ! ${#cols[@]} = 0 ]; then
        if [ "${cur:${#cur}-1}" = "," ]; then
          cols+=("")
        fi

        curcol=${cols[${#cols[@]}-1]}
        others=$(_comp_marathon_join-str , "${cols[@]:0:${#cols[@]}-1}")
      else
        others=""
        curcol=""
      fi

      COMPREPLY+=( $(compgen -W "default id processedOffersCount unusedOffersCount lastUsedOfferAt count since overdue delay rejections UnfulfilledRole UnfulfilledConstraint NoCorrespondingReservationFound AgentMaintenance InsufficientCpus InsufficientMemory InsufficientDisk InsufficientGpus InsufficientPorts DeclinedScarceResources" -- "${curcol}"))
      if [ ! -z "$others" ]; then
        for ((n=0; n<${#COMPREPLY[@]}; n++)); do
          COMPREPLY[$n]="${others},${COMPREPLY[n]}"
        done
      fi

      return 0
      ;;
  esac
}

_comp_marathon_app_list() {
  case "${cur}" in
    -*)
      COMPREPLY+=( $(compgen -W "--all --sort -s --columns -c --no-header --no-align --help" -- "${cur}"))
      return 0
      ;;
  esac

  case "${prev}" in
    -c|--columns|-s|--sort)
      local cols curcol others n
      cols=($(echo "$cur" | tr ',' ' '))
      if [ ! ${#cols[@]} = 0 ]; then
        if [ "${cur:${#cur}-1}" = "," ]; then
          cols+=("")
        fi

        curcol=${cols[${#cols[@]}-1]}
        others=$(_comp_marathon_join-str , "${cols[@]:0:${#cols[@]}-1}")
      else
        others=""
        curcol=""
      fi

      COMPREPLY+=( $(compgen -W "default id cmd cpus mem disk gpus executor backoffSeconds backoffFactor maxLaunchDelaySeconds version residency killSelection requirePorts taskCounts tasksStaged tasksRunning tasksHealthy tasksUnhealthy ports container-type docker-network-type volume-count docker-image lastScalingAt lastConfigChangeAt deploymentCount hcCount hcType instances" -- "${curcol}"))
      if [ ! -z "$others" ]; then
        for ((n=0; n<${#COMPREPLY[@]}; n++)); do
          COMPREPLY[$n]="${others},${COMPREPLY[n]}"
        done
      fi

      return 0
      ;;
  esac
}

_comp_marathon() {
  local cur prev words cword
  _init_completion -n : || return
  COMPREPLY=()

  if [ ${COMP_CWORD} = 1 ]; then
    COMPREPLY=( $(compgen -W "curl app queue app pod kill" -- ${cur}) )

    return 0
  fi

  cmd=${COMP_WORDS[1]}

  case "$cmd" in
    curl)
      _comp_marathon_curl
      ;;
    pod)
      _comp_marathon_pod
      ;;
    app)
      _comp_marathon_app
      ;;
    queue)
      _comp_marathon_queue
      ;;
    apps)
      _comp_marathon_apps
      ;;
    *)
      return 0
      ;;
  esac

}
complete  -o nospace -o bashdefault -F _comp_marathon marathon-cli
complete  -o nospace -o bashdefault -F _comp_marathon mar
