#!/bin/bash

_comp_mesos_join-str() {
  delimiter="$1"
  shift
  OUTPUT=""
  for ((n=1; n<=$#; n++)); do
    if [ "$n" -ne 1 ]; then
      OUTPUT+="${delimiter}"
    fi
    OUTPUT+="${!n}"
  done
  echo -n "$OUTPUT"
}

_comp_mesos_curl() {
  case "${prev}" in
    curl)
      COMPREPLY+=( $(compgen -W "/files/browse /files/browse.json /files/debug /files/debug.json /files/download /files/download.json /files/read /files/read.json /logging/toggle /api/v1 /api/v1/scheduler /create-volumes /destroy-volumes /flags /frameworks /health /machine/down /machine/up /maintenance/schedule /maintenance/status /quota /redirect /reserve /roles /roles.json /slaves /state /state-summary /state.json /tasks /tasks.json /teardown /unreserve /weights /metrics/snapshot /profiler/start /profiler/stop /registrar(id)/registry /system/stats.json /version" -- "${cur}"))
      return 0
      ;;
  esac
}

_comp_mesos_tasks() {
  case "${cur}" in
    -*)
      COMPREPLY+=( $(compgen -W "--all -a --limit -l --sort -s --columns -c --no-header --no-align --help" -- "${cur}"))
      return 0
      ;;
  esac

  case "${prev}" in
    -c|--columns|-s|--sort)
      local cols curcol others n
      cols=($(echo "$cur" | tr ',' ' '))
      if [ ! ${#cols[@]} = 0 ]; then
        if [ "${cur:${#cur}-1}" = "," ]; then
          cols+=("")
        fi

        curcol=${cols[${#cols[@]}-1]}
        others=$(_comp_mesos_join-str , "${cols[@]:0:${#cols[@]}-1}")
      else
        others=""
        curcol=""
      fi

      COMPREPLY+=( $(compgen -W "default id name cpus mem gpus disk ports state type image host ip ips url started finished framework_id executor_id agent_id region zone domain docker-image role" -- "${curcol}"))
      if [ ! -z "$others" ]; then
        for ((n=0; n<${#COMPREPLY[@]}; n++)); do
          COMPREPLY[$n]="${others},${COMPREPLY[n]}"
        done
      fi

      return 0
      ;;
  esac
}

_comp_mesos_agents() {
  case "${cur}" in
    -*)
      COMPREPLY+=( $(compgen -W "--all -a --sort -s --columns -c --no-header --no-align --help" -- "${cur}"))
      return 0
      ;;
  esac

  case "${prev}" in
    -c|--columns|-s|--sort)
      local cols curcol others n
      cols=($(echo "$cur" | tr ',' ' '))
      if [ ! ${#cols[@]} = 0 ]; then
        if [ "${cur:${#cur}-1}" = "," ]; then
          cols+=("")
        fi

        curcol=${cols[${#cols[@]}-1]}
        others=$(_comp_mesos_join-str , "${cols[@]:0:${#cols[@]}-1}")
      else
        others=""
        curcol=""
      fi

      COMPREPLY+=( $(compgen -W "default id hostname region zone domain port version active pid roles attributes cpus mem disk gpus ports used-cpus used-mem used-disk used-gpus reserved-cpus reserved-mem reserved-disk reserved-gpus unreserved-cpus unreserved-mem unreserved-disk unreserved-gpus registered" -- "${curcol}"))
      if [ ! -z "$others" ]; then
        for ((n=0; n<${#COMPREPLY[@]}; n++)); do
          COMPREPLY[$n]="${others},${COMPREPLY[n]}"
        done
      fi

      return 0
      ;;
  esac

}
      
_comp_mesos_frameworks() {
  case "${cur}" in
    -*)
      COMPREPLY+=( $(compgen -W "--all -a --sort -s --columns -c --no-header --no-align --help" -- "${cur}"))
      return 0
      ;;
  esac

  case "${prev}" in
    -c|--columns|-s|--sort)
      local cols curcol others n
      cols=($(echo "$cur" | tr ',' ' '))
      if [ ! ${#cols[@]} = 0 ]; then
        if [ "${cur:${#cur}-1}" = "," ]; then
          cols+=("")
        fi

        curcol=${cols[${#cols[@]}-1]}
        others=$(_comp_mesos_join-str , "${cols[@]:0:${#cols[@]}-1}")
      else
        others=""
        curcol=""
      fi

      COMPREPLY+=( $(compgen -W "default tasks-statuses id hostname pid name offered-disk offered-mem offered-gpus offered-cpus used-disk used-mem used-gpus used-cpus tasks-staging tasks-starting tasks-running tasks-killing tasks-finished tasks-killed tasks-failed tasks-lost tasks-error tasks-unreachable active web_ui capabilities registered unregistered failover_timeout role recovered user connected principal" -- "${curcol}"))
      if [ ! -z "$others" ]; then
        for ((n=0; n<${#COMPREPLY[@]}; n++)); do
          COMPREPLY[$n]="${others},${COMPREPLY[n]}"
        done
      fi

      return 0
      ;;
  esac

}


_comp_mesos_sandbox() {
  case "${cur}" in
    -*)
      COMPREPLY+=( $(compgen -W "--u --url" -- "${cur}"))
      return 0
      ;;
  esac
}

_comp_mesos_agent() {
  case "${cur}" in
    -*)
      COMPREPLY+=( $(compgen -W "--u --url" -- "${cur}"))
      return 0
      ;;
    *)
      COMPREPLY+=( $(compgen -W "$(mesos-cli agents -c id --no-header --no-align)" -- "${cur}"))
      return 0
      ;;
  esac
}

_comp_mesos_task() {
  case "${cur}" in
    -*)
      COMPREPLY+=( $(compgen -W "--u --url" -- "${cur}"))
      return 0
      ;;
    *)
      COMPREPLY+=( $(compgen -W "$(mesos-cli tasks -c id --no-header --no-align)" -- "${cur}"))
      return 0
      ;;
  esac
}

_comp_mesos() {
  local cur prev words cword
  _init_completion -n : || return
  COMPREPLY=()

  if [ ${COMP_CWORD} = 1 ]; then
    COMPREPLY=( $(compgen -W "curl executor-url task agent agents frameworks tasks sandbox" -- ${cur}) )

    return 0
  fi

  cmd=${COMP_WORDS[1]}

  case "$cmd" in
    executor-url)
      _comp_mesos_executor_url
      ;;
    agent)
      _comp_mesos_agent
      ;;
    inspect|task)
      _comp_mesos_task
      ;;
    curl)
      _comp_mesos_curl
      ;;
    frameworks)
      _comp_mesos_frameworks
      ;;
    ps|tasks)
      _comp_mesos_tasks
      ;;
    sandbox)
      _comp_mesos_sandbox
      ;;
    agents)
      _comp_mesos_agents
      ;;
    *)
      return 0
      ;;
  esac

}
complete  -o nospace -o bashdefault -F _comp_mesos mesos
complete  -o nospace -o bashdefault -F _comp_mesos mesos-cli
complete  -o nospace -o bashdefault -F _comp_mesos mcli
