#!/usr/local/bin/bash

export MCLIPATH=$(cd $(dirname $0)/..; pwd)
if [ -z "$ENTERED" ]; then
  export PATH=$MCLIPATH:$MCLIPATH/osx:$PATH
  source /usr/local/share/bash-completion/bash_completion
fi

export ENTERED=1

echo "Loaded mcli shell / env"
exec /usr/local/bin/bash --rcfile $MCLIPATH/osx/mclirc

diagnostic_curl() {
  export MESOS_CURL_CMD=$MCLIPATH/diagnostic-curl
  export MARATHON_CURL_CMD=$MCLIPATH/diagnostic-curl
}
